#!/data/data/com.termux/files/usr/bin/bash
clear
color=$'\e[0m'

echo -e "\e[031m" "          ▄▀▄     ▄▀▄"
echo -e "\e[031m" "         ▄█░░▀▀▀▀▀░░█▄"
echo -e "\e[031m" "     ▄▄  █░░░░░░░░░░░█  ▄▄"
echo -e "\e[031m" "    █▄▄█ █░░█░░┬░░█░░█ █▄▄█"
echo -e "\e[036m" "╔════════════════════════════════════════╗"                                                                          
echo -e "\e[032m" "║ ♚ Project Name : Termux-YDL            ║"
echo -e "\e[032m" "║ ♚ Author : Ak500                       ║"
echo -e "\e[032m" "║ ♚ Github : g̲i̲t̲h̲u̲b̲.̲c̲o̲m̲/̲ak500k/̲          ║"
echo -e "\e[036m" "╠════════════════════════════════════════╝"
echo -e "\e[036m" "╠═▶ [𝗦𝗲𝗹𝗲𝗰𝘁 𝗔 𝗙𝗼𝗿𝗺𝗮𝘁]  ➳"
echo -e "\e[032m" "╠═▶ 1. Music Mp3♫"
echo -e "\e[032m" "╠═▶ 2. Video 360p"
echo -e "\e[032m" "╠═▶ 3. Video 480p"
echo -e "\e[032m" "╠═▶ 4. Video 720p"
echo -e "\e[032m" "╠═▶ 5. Video 1080p"
echo -e "\e[032m" "╠═▶ 6. Video 2160p"
echo -e "\e[032m" "╠═▶ 7. Exit Termux-YDL" 

printf "\e[032m ╚═:➤  $color"
while :
do

  read INPUT_STRING
  case $INPUT_STRING in

	  1)
		echo "$command --no-mtime -o /data/data/com.termux/files/home/storage/shared/YouTube/%(title)s.%(ext)s -f 'bestaudio[ext=mp3]' --audio-format mp3" > ~/.config/youtube-dl/config #option 1
    	youtube-dl $1
		;;

	  2)

		echo "$command --no-mtime -o /data/data/com.termux/files/home/storage/shared/YouTube/%(title)s.%(ext)s -f 'bestvideo[height<=360][ext=mp4]+bestaudio[ext=m4a]'" > ~/.config/youtube-dl/config #option 1
    	youtube-dl $1
		;;
		
	  3) 
		echo "$command --no-mtime -o /data/data/com.termux/files/home/storage/shared/YouTube/%(title)s.%(ext)s -f 'bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]'" > ~/.config/youtube-dl/config #option 1
    	youtube-dl $1
		;;
  	  4) 
		echo "$command --no-mtime -o /data/data/com.termux/files/home/storage/shared/YouTube/%(title)s.%(ext)s -f 'bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]'" > ~/.config/youtube-dl/config #option 1
    	youtube-dl $1
		;;
	
	  5)
		echo "$command --no-mtime -o /data/data/com.termux/files/home/storage/shared/YouTube/%(title)s.%(ext)s -f 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]'" > ~/.config/youtube-dl/config #option 1
    	youtube-dl $1
		;;

	  6)
		echo "$command --no-mtime -o /data/data/com.termux/files/home/storage/shared/YouTube/%(title)s.%(ext)s -f 'bestvideo[height<=2160][ext=mp4]+bestaudio[ext=m4a]'" > ~/.config/youtube-dl/config #option 1
    	youtube-dl $1
		;;

	  7) 
		break
        ;;
		
	  *)
	     
	    echo -e "\e[031m \n Worng input! Please Enter again::\n$color"
		;;
  esac
  done
